name: PR

on:
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        host: [ ubuntu-latest, windows-latest ]
    runs-on: ${{matrix.host}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0-dev.3017+da94227f7

      - run: zig version
      - run: zig env
      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod version
      - run: zigmod ci
      - run: zig build
      - run: ./zig-out/bin/ghr
