name: Push

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - run: zig version
      - run: zig env
      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod version
      - run: zigmod ci
      # - run: ./build_all.sh
      - run: ./make_release.sh ${{ secrets.GITHUB_TOKEN }}
