name: Push

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --all --tags

      - uses: mlugg/setup-zig@v1
        with:
          mirror: "http://mirrors.nektro.net/s3cgi"
          version: 0.13.0

      - run: zig version
      - run: zig env

      - uses: nektro/actions-setup-zigmod@v1

      - run: zigmod version
      - run: zigmod ci
      - run: zig build all
      - run: ./changelog.sh
      - run: ./make_release.sh ${{ secrets.GITHUB_TOKEN }}
